---

# Test of performance 
- name: Jmeter testing in phonebook app
  hosts: preprod
  become: true
  gather_facts: true

  vars_files:
    - "vars/main.yml"

   
  pre_tasks:
  - name: update all packages 
    yum:
      name: '*'
      update_only: yes
      update_cache: yes
      state: latest

  - name: install wget
    yum:
      name: wget
      state: installed 


  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk

  tasks:
  - name: Using wget to apache jmeter
    shell: "wget http://www.gtlib.gatech.edu/pub/apache/jmeter/binaries/apache-jmeter-{{ apache_jmeter_version }}.tgz"
    args:
      warn: no

  - name: unzip a file
    command: "tar xf apache-jmeter-{{ apache_jmeter_version }}.tgz"
    args:
      warn: no

  - name: Run the test with jmx_file
    shell: "apache-jmeter-{{ apache_jmeter_version }}/bin/jmeter.sh -n -t plan_test_jmeter.jmx  -l report.jtl"
    args:
      warn: no

