---

# phonebook playbook
- name: phonebook deployment playbook
  hosts: build preprod prod
  gather_facts: yes
  become: true


  vars_files:
    - "vars/secret.yml"
    - "vars/main.yml"

  vars:
    pip_install_packages:
      - name: docker

  pre_tasks:
    - block:
      - name: update all packages
        yum:
          name: '*'
          update_only: yes
          update_cache: yes
          state: present

      - name: Install epel release
        yum:
          name: epel-release
          state: installed
      tags:
        - always

  roles:
    - { role: geerlingguy.pip, tags: [ always ] }
    - { role: geerlingguy.docker, tags: [ always ] }
    - { role: geerlingguy.git, tags: [ always ] }
    - { role: phonebook-app }
