---

# phonebook playbook
- name: phonebook deployment playbook
  hosts: build preprod prod
  gather_facts: yes
  become: true


  vars_files:
    - "vars/secret.yml"
    - "vars/main.yml"

  vars:
    pip_install_packages:
      - name: docker

    pip_package: python-pip

    pip_executable: pip

  pre_tasks:
    - block:
      - name: update all packages
        yum:
          name: '*'
          update_only: yes
          update_cache: yes
          state: present

      - name: Install EPEL repo
        package: name=epel-release state=present
        when: ansible_distribution == "CentOS"

      - name: install python-pip
        package: name=python-pip state=present update_cache=yes
 
      - name: install zabbix packages
        yum: 
          name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
          state: present


      - name: install zabbix agent
        yum:
          name: zabbix-agent
          state: installed

      - name: copy zabbix agent zabbix-agentd.j2 in zabbix-agentd.conf
        template:
          src: templates/zabbix/zabbix_agentd.j2
          dest: /etc/zabbix/zabbix_agentd.conf
          owner: root
          group: root
          mode: '0644'
 
      - name: Restart web service
        service:
          name: zabbix-agent
          state: started

      tags:
        - always

  roles:
    - { role: geerlingguy.pip, tags: [ always ] }
    - { role: geerlingguy.docker, tags: [ always ] }
    - { role: geerlingguy.git, tags: [ always ] }
    - { role: phonebook-app }
