---


# deployment role of phonebook app

- name: create project directory
  file:
    path: "{{ home }}/final-project"
    state: directory
  tags:
    - build
    - preprod
    - prod

- name: copy devops private key file
  copy:
    content: "{{ github_private_key }}"
    dest: "{{ home }}/.ssh/id_rsa"
    owner: centos
  tags:
    - build
    - preprod
    - prod

- name: copy test plan file in the remote machine
  template:
    src: templates/plan_test_jmeter.j2
    dest: "{{ home }}/plan_test_jmeter.jmx"
    owner: centos
    remote_src: no
  tags:
    - preprod
    - prod


- name: load the source code in github
  git:
    repo: "{{ repo_fake_backend  }}"
    dest: "{{ home }}/final-project"
    accept_hostkey: yes
    force: yes
    recursive: no
    key_file: "{{ home }}/.ssh/id_rsa"
    version: "{{ branch_clone }}"
  tags:
    - build
    - preprod
    - prod


- name: copy insecure-registry in daemon.json
  template:
    src: templates/daemon.j2
    dest: "{{ docker_path }}/daemon.json"
    owner: centos
  tags:
    - build
    - preprod
    - prod

- name: Restart service docker
  service:
    name: docker
    state: restarted
  tags:
    - build
    - preprod
    - prod

- name: Log into DockerHub
  docker_login:
    registry: "{{ address_registry }}:{{ port_registry }}"
    username: "{{ dockerhub_login_vault }}"
    password: "{{ dockerhub_pwd_vault }}"
  tags:
    - build
    - preprod
    - prod

- name: Create a global network of our two containers
  docker_network:
    name: phonebook_network
  tags:
    - preprod
    - prod

- block:
  - name: Build phonebook-mysql 
    docker_image:
      build:
        path: "{{ home }}/final-project"
        dockerfile: Dockerfile-mysql
      name: "{{ address_registry }}:{{ port_registry }}/phonebook_repo/phonebook-image-mysql"
      state: present
      source: build
      tag: "{{ tag_version }}"

  - name: Build phonebook-app 
    docker_image:
      build:
        path: "{{ home }}/final-project"
        dockerfile: Dockerfile-app
      name: "{{ address_registry }}:{{ port_registry }}/phonebook_repo/phonebook-image-app"
      state: present
      source: build
      tag: "{{ tag_version }}"
  tags:
    - build

- block:
  - name: Build phonebook-mysql
    docker_image:
      build:
        path: "{{ home }}/final-project"
        dockerfile: Dockerfile-mysql
      name: "{{ address_registry }}:{{ port_registry }}/phonebook_repo/phonebook-image-mysql"
      state: present
      source: build
      push: yes
      tag: "{{ tag_version }}"

  - name: Build phonebook-app
    docker_image:
      build:
        path: "{{ home }}/final-project"
        dockerfile: Dockerfile-app
      name: "{{ address_registry }}:{{ port_registry }}/phonebook_repo/phonebook-image-app"
      state: present
      source: build
      push: yes
      tag: "{{ tag_version }}"
  tags:
    - push


- block:
  - name: pull image of phonebook-mysql
    docker_image:
      name: "{{ address_registry }}:{{ port_registry }}/phonebook_repo/phonebook-image-mysql:{{ tag_version }}"
      source: pull

  - name: pull image of phonebook-app
    docker_image:
      name: "{{ address_registry }}:{{ port_registry }}/phonebook_repo/phonebook-image-app:{{ tag_version }}"
      source: pull
  tags:
    - prod


- block:
  - name: container phonebook mysql
    docker_container:
      name: phonebook-mysql
      image: "{{ address_registry }}:{{ port_registry }}/phonebook_repo/phonebook-image-mysql:{{ tag_version }}"
      state: started
      restart: yes
      networks:
        - name: phonebook_network

  - name: sleep for 20 seconds and continue with play
    wait_for:
      timeout: 20

  - name: container phonebook app
    docker_container:
      name: phonebook-app
      image: "{{ address_registry }}:{{ port_registry }}/phonebook_repo/phonebook-image-app:{{ tag_version }}"
      state: started
      ports:
        - "8181:8181"
      restart: yes
      networks:
        - name: phonebook_network
  tags:
    - preprod
    - prod

- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
    url: "http://{{ adresse_preprod }}:{{ port_preprod }}"
  tags:
    - test
